### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
### Ajouter une visite
POST http://localhost:8080/api/visites
Content-Type: application/json

{
  "dateVisite": "2025-10-20",
  "format": "PRESENTIEL",
  "commentaire": "Première visite pédagogique",
  "apprenti": {
    "id": 1
  },
  "tuteurEnseignant": {
    "id": 1
  },
  "maitreApprentissage": {
    "id": 1
  }
}

###
### Récupérer toutes les visites
GET http://localhost:8080/api/visites

###
### Récupérer une visite par ID
GET http://localhost:8080/api/visites/1

###
### Modifier une visite
PUT http://localhost:8080/api/visites/1
Content-Type: application/json

{
  "dateVisite": "2025-10-21",
  "format": "VISIO",
  "commentaire": "Changement de format en visio",
  "apprenti": {
    "id": 1
  },
  "tuteurEnseignant": {
    "id": 1
  },
  "maitreApprentissage": {
    "id": 1
  }
}

###
### Supprimer une visite
DELETE http://localhost:8080/api/visites/1