### Ajouter une entreprise
POST http://localhost:8080/api/entreprises
Content-Type: application/json

{
  "raisonSociale": "Société Générale",
  "adresse": "19 Cr Valmy",
  "infosUtilesAcces": "Badge rez-de-chaussée"
}

###
### Récupérer toutes les entreprises
GET http://localhost:8080/api/entreprises

###
### Récupérer une entreprise par ID
GET http://localhost:8080/api/entreprises/1

###
### Supprimer une entreprise
DELETE http://localhost:8080/api/entreprises/1

###
### Modifier une entreprise (PUT)
PUT http://localhost:8080/api/entreprises/1
Content-Type: application/json

{
  "raisonSociale": "Entreprise XXX",
  "adresse": "456 avenue de Paris",
  "infosUtilesAcces": "Accès par la porte B - 2e étage"
}