### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
### Ajouter une formation
POST http://localhost:8080/formations
Content-Type: application/json

{
  "intitule": "Développement Full Stack JAVA",
  "description": "Formation complète sur Spring Boot et JAVA",
  "duree": 30
}

###

###  Récupérer toutes les formations
GET http://localhost:8080/formations/api

###

### Récupérer une formation par ID
GET http://localhost:8080/formations/1

###

###  Modifier une formation
PUT http://localhost:8080/formations/1
Content-Type: application/json

{
  "intitule": "Développement Full Stack Java Avancé",
  "description": "Spring Boot + JAVA + Microservices",
  "duree": 50
}

###

###  Supprimer une formation
DELETE http://localhost:8080/formations/1