### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Créer un maître d'apprentissage
POST http://localhost:8080/api/maitres
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "poste": "Chef de projet",
  "email": "jean.dupont@entreprise.com",
  "telephone": "0601020304",
  "remarques": ""
}

###
### Récupérer tous les maîtres
GET http://localhost:8080/api/maitres

###
### Récupérer un maître par ID
GET http://localhost:8080/api/maitres/1

###
### Modifier un maître d'apprentissage
PUT http://localhost:8080/api/maitres/1
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean-Pierre",
  "poste": "Responsable technique",
  "email": "jeanpierre.dupont@entreprise.com",
  "telephone": "0601020305",
  "remarques": "A changé de poste récemment"
}

###
### Supprimer un maître d'apprentissage
DELETE http://localhost:8080/api/maitres/1